# Generated by Django 5.0.3 on 2024-03-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokitem',
            name='color',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.colors'),
        ),
    ]
