# Generated by Django 5.0.3 on 2024-03-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_stokitem_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
