# Generated by Django 5.0.3 on 2024-03-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_colors_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='done',
        ),
    ]
