# Generated by Django 5.0.3 on 2024-03-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_completed_order_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_completed',
            new_name='complete_date',
        ),
    ]
