# Generated by Django 5.0.3 on 2024-04-28 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_payment_aprove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cep',
            new_name='postal_code',
        ),
    ]
